### ISSUE TITLE
Создать презентацию 

### ISSUE THREAD

**Issue by SixDevelop** [developeum/project#1]
Необходимо написать в своём гугл доке факты о себе(это пойдёт на все 3 презентации), что каждый может предложить для каждого проекта. Ссылку на файл необходимо приложить в комментариях к этому issues и по этому я буду понимать что вы выполнили свою часть.

**Comment by SixDevelop** [comment]
https://docs.google.com/document/d/1oCoMaQ_8Ksvo7ljU6g7G0ZFXySDY_Gn35rKVSC74Qt0/edit?usp=sharing

**Comment by alinadmb** [comment]
https://docs.google.com/document/d/1q4IDH09mPTqa7KrUjTYI4_6cjtlwKQiPqM98nRBQhJU/edit?usp=sharing

**Comment by SixDevelop** [comment]
1 слайд приветствие, название команды
2 слайд перечисление участников + 3 курс, все знакомы с базовыми концепциями программирования
3 Сергей Нестеров
4 Герман Риттер
5 Михаил Тимофеев
6 Наталья Мищенкова
7 Алина Дамбаева
8 DS
9 Backend
10 Frontend
11 Вариант решения проблемы(КЕРН)
12 Окончание

**Comment by ghost** [comment]
https://docs.google.com/document/d/13SCXauTLfsEd8uKmohyzRbxOeyho5dyyMoRV92w5V_I/edit?usp=drivesdk

**Comment by exp101t** [comment]
https://docs.google.com/document/d/1OvKdTqnEuhlFF4yAxqoN0xkvI85oSyOxxtvNboHE27Q/edit?usp=sharing
